version: 2
before:
  hooks:
    - go mod download
archives:
  - id: darwin
    ids:
      - darwin
    formats:
      - zip
  - id: linux
    ids:
      - linux
    formats:
      - zip
  - id: windows
    ids:
      - windows
    formats:
      - zip
homebrew_casks:
  - ids:
      - darwin
    binaries:
      - "{{.ProjectName}}"
    repository:
      owner: attachmentgenie
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.commit={{.ShortCommit}}"
      - -X "main.date={{.Date}}"
      - -X "main.version={{.Version}}"
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.commit={{.ShortCommit}}"
      - -X "main.date={{.Date}}"
      - -X "main.version={{.Version}}"
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X "main.commit={{.ShortCommit}}"
      - -X "main.date={{.Date}}"
      - -X "main.version={{.Version}}"
dockers_v2:
  - images:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}"
    tags:
      - "{{ .Version }}"
      - "v{{ .Major }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.description": "Foo bar"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title=": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.ShortCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
nfpms:
  - id: linux
    maintainer: 'bram vogelaar <bram@attachmentgenie.com>'
    package_name: "{{.ProjectName}}"
    ids:
      - linux
    formats:
      - deb
      - rpm
sboms:
  - artifacts: archive
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
