before:
  hooks:
    - go mod download
archives:
  - id: darwin
    builds:
    - darwin
    format: zip
  - id: linux
    builds:
    - linux
    format: zip
  - id: windows
    builds:
      - windows
    format: zip
brews:
  - ids:
      - darwin
    folder: Formula
    install: |
      bin.install "{{.ProjectName}}"
    repository:
      owner: attachmentgenie
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
builds:
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
dockers:
  - image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.source https://github.com/attachmentgenie/{{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    goarm: "8"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.source https://github.com/attachmentgenie/{{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
nfpms:
  - id: darwin
    maintainer: 'bram vogelaar <bram@attachmentgenie.com>'
    package_name: "{{.ProjectName}}"
    builds:
      - linux
    formats:
      - deb
      - rpm
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
